#!/bin/bash -e

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

BUILD_DIR="${ROOT}/build"

rm -rf "${BUILD_DIR}"
rsync \
        -r \
        --copy-links \
        --exclude 'composer.*' \
        --exclude '.git' \
        --exclude '.git*' \
        --exclude 'LICENSE' \
        --exclude 'Tests' \
        --exclude 'Test' \
        --exclude 'examples-*' \
        --exclude 'tests' \
        --exclude 'docs' \
        --exclude '*.txt' \
        --exclude 'docs-*' \
        --exclude '.docker' \
        --exclude '*.md' \
        --exclude 'aws-sdk-php/features' \
        "${ROOT}/vendor" "${BUILD_DIR}"
cp -r "${ROOT}/dynamic/"* "${BUILD_DIR}"
cp -r "${ROOT}/static/"* "${BUILD_DIR}"
