#!/bin/bash -e

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

BUILD_DIR="${ROOT}/build"
LAMBDA_ZIP="${BUILD_DIR}/lambda.zip"

rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}"
cp -r "${ROOT}/vendor" "${BUILD_DIR}"
cp -r "${ROOT}/dynamic/"* "${BUILD_DIR}"
cp -r "${ROOT}/static/"* "${BUILD_DIR}"

rm -f "${LAMBDA_ZIP}"
(
    cd "${BUILD_DIR}"
    zip -r "${LAMBDA_ZIP}" *
)
